### ISSUE TITLE
blueprint files missing from commit

### ISSUE THREAD

**Issue by JoshFord0** [Mitalee/Flask-SocketIO-celery-Docker#1]
Hello - I was interested in learning from this repo however the files in the blueprints folder were not included within the commit. Can you reupload? Thanks for putting this example together.

**Comment by Mitalee** [comment]
Yes I will just check. Could you give me a day?

**Comment by JoshFord0** [comment]
Sure, thanks I appreciate it!

**Comment by Mitalee** [comment]
Done. also added a couple of screenshots in the readme.
